name: Build pdoc documentation
description: "Build pdoc documentation"

inputs:
  source-folder:
    description: 'Source folder to generate documentation for'
    type: string
    required: false
    default: 'cvx'
  pdoc-arguments:
    description: 'Additional pdoc command line arguments'
    type: string
    required: false
    default: ''
  working-directory:
    description: 'Directory where the Python project is located'
    required: false
    default: '.'


runs:


  using: "composite"
  steps:
    - name: Update pip
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Ensure pip is installed and up-to-date
        python -m ensurepip --upgrade

    - name: Install and build pdoc
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mkdir -p artifacts/pdoc
        python -m pip install --no-cache-dir pdoc
        pdoc -o artifacts/pdoc ${{ inputs.pdoc-arguments }} ${{ inputs.source-folder }}

    - name: Upload documentation
      if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
      uses: actions/upload-artifact@v4
      with:
        name: pdoc
        path: ${{ inputs.working-directory }}/artifacts/pdoc
        retention-days: 1
