# Ruff configuration for tschm/.config-templates

# Maximum line length
line-length = 120

# Target Python version
target-version = "py312"

# Exclude template folder (with placeholders)
exclude = ["template/src/**/*"]

[lint]
# Linting rules to select
select = ["D", "E", "F", "I", "W", "UP"]

# Ignore specific rules
ignore = ["N999"]

[lint.pydocstyle]
# Use Google docstring convention
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"