# Ruff configuration for tschm/.config-templates

# Maximum line length
line-length = 120

# Target Python version
target-version = "py312"

# Exclude template folder (with placeholders)
exclude = ["template/src/*"]

# Linting rules to select
select = ["D", "E", "F", "I", "N", "W", "UP"]

# Pydocstyle settings
[pydocstyle]
convention = "google"

# Formatting rules
[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"