name: Bump version and publish

on:
  workflow_dispatch:

jobs:
  tag:
    permissions:
      contents: write

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        uses: tschm/cradle/actions/tag@main
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in pyproject.toml
        shell: bash
        run: |
          echo "Updating version to ${{ steps.tag_version.outputs.new_tag }}"
          sed -i "s/0.0.0/${{ steps.tag_version.outputs.new_tag }}/" pyproject.toml

      - name: Build package
        shell: bash
        run: |
          hatch build

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1

      - name: Create GitHub release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true
          files: dist/*

  publish:
    needs: tag
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: read
      # This permission is required for trusted publishing.
      id-token: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
