name: Convert Marimo to HTML
description: "Converts Marimo .py files to HTML format for documentation"

inputs:
  source_folder:
    description: 'Source directory containing Marimo .py files'
    required: false
    default: 'book/marimo'


runs:
  using: composite
  steps:
    - name: Update pip
      shell: bash
      run: |
        # Ensure pip is installed and up-to-date
        python -m ensurepip --upgrade

    - name: Install marimo
      shell: bash
      run: |
        python -m pip install --no-cache-dir marimo

    - name: Create output directory
      shell: bash
      run: |
        mkdir -p artifacts/marimo

    - name: Convert Marimo files to HTML
      shell: bash
      run: |
        if [ ! -d "${{ inputs.source_folder }}" ]; then
          echo "Error: Source directory ${{ inputs.source_folder }} does not exist"
          exit 1
        fi

        found_files=0
        for file in "${{ inputs.source_folder }}"/*.py; do
          if [ -f "$file" ]; then
            found_files=1
            filename=$(basename "$file" .py)
            echo "Converting $filename.py to HTML..."
            marimo export html "$file" -o "artifacts/marimo/${filename}.html"
          fi
        done

        if [ "$found_files" -eq 0 ]; then
          echo "Warning: No .py files found in ${{ inputs.source_folder }}"
          exit 0
        fi

    - name: Upload HTML artifacts
      if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
      uses: actions/upload-artifact@v4
      with:
        name: marimo
        path: artifacts/marimo
        retention-days: 1
