name: Build the Jupyter Book
description: "Build jupyter book"

inputs:
  working-directory:
    description: 'Directory where the Python project is located'
    required: false
    default: '.'

runs:
  using: "composite"

  steps:
    - name: Update pip
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Ensure pip is installed and up-to-date
        python -m ensurepip --upgrade

    - name: Install jupyterbook
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        python -m pip install --no-cache-dir jupyter-book sphinx-math-dollar

    # Build the book
    - name: Build the book
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        jupyter-book clean book
        jupyter-book build book

    # Upload the book
    - name: Archive book
      if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: ${{ inputs.working-directory }}/book/_build/html/
        retention-days: 1
