name: CI

on:
  push

jobs:
  test-template-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Launch the cradle
        uses: tschm/cradle/actions/cradle@v0.1.56
        with:
          python-version: '3.12'

      - name: Test ci flow
        uses: tschm/cradle/actions/flow@v0.1.56
        with:
          workflow: ci.yml
