name: Test Template Workflows

on:
  push:

jobs:
  test-template-workflows:
    strategy:
      matrix:
        python-version: [ '3.12' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install act
        run: |
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          # Add the installation directory to PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Verify act installation
        run: |
          act --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}