name: CI

on:
  push:

jobs:
  test-template-workflows:
    strategy:
      matrix:
        python-version: [ '3.12' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Launch the cradle
        uses: tschm/cradle/actions/cradle@main
        with:
          python-version: '3.12'

      - name: Run copier
        working-directory: .
        shell: bash
        run: |
          copier copy --vcs-ref HEAD . template --data-file .github/resources/data.yaml --skip

      - name: Check template
        working-directory: template
        shell: bash
        run : |
          cat src/tests/conftest.py

      - name: Prepare the repo
        working-directory: template
        shell: bash
        run: |
          # otherwise the pre-commit hooks won't "see" files
          # also act needs to have the commit in place
          git init -b main
          git add .
          git commit -m "Initial commit"

      - name: Test ci flow
        uses: tschm/cradle/actions/flow@main
        with:
          working-directory: template
          workflow: ci.yml

      - name: Test pre-commit flow
        uses: tschm/cradle/actions/flow@main
        with:
          working-directory: template
          workflow: pre-commit.yml

      - name: Test book flow
        uses: tschm/cradle/actions/flow@main
        with:
          working-directory: template
          workflow: book.yml
