name: CI

on:
  push:

jobs:
  test-template-workflows:
    strategy:
      matrix:
        python-version: [ '3.12' ]

    runs-on: ubuntu-latest

    steps:
      - name: Launch the cradle
        uses: tschm/cradle/actions/cradle@2.2.5
        with:
          python-version: '3.12'
          destination-path: 'template'

      - name: Test ci flow
        uses: tschm/cradle/actions/flow@2.2.5
        with:
          working-directory: template
          workflow: ci.yml

      - name: Test pre-commit flow
        uses: tschm/cradle/actions/flow@2.2.5
        with:
          working-directory: template
          workflow: pre-commit.yml

      - name: Test book flow
        uses: tschm/cradle/actions/flow@2.2.5
        with:
          working-directory: template
          workflow: book.yml
