name: BOOK

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Launch the cradle
        uses: tschm/cradle/actions/cradle@v0.1.55
        with:
          python-version: '3.12'

      - name: Test book flow
        uses: tschm/cradle/actions/flow@v0.1.54
        with:
          workflow: book.yml
