name: "ci"

on:
- push

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'

      - name: Set up Python environment with uv
        shell: bash
        run: |
          # Create venv
          uv venv
          uv pip install copier pytest
          uv run pytest tests
