name: pre-commit

on:
  push:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: '--verbose --all-files'

  pre-commit-template:
    runs-on: ubuntu-latest

    steps:
      - name: Launch the cradle
        uses: tschm/cradle/actions/cradle@main
        with:
          python-version: '3.12'

      - name: Test pre-commit flow
        uses: tschm/cradle/actions/flow@main
        with:
          workflow: pre-commit.yml
