name: pre-commit

on:
  push:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: tschm/cradle/actions/pre-commit@v0.1.57


  pre-commit-template:
    runs-on: ubuntu-latest

    steps:
      - name: Launch the cradle
        uses: tschm/cradle/actions/cradle@v0.1.57
        with:
          python-version: '3.12'

      - name: Test pre-commit flow
        uses: tschm/cradle/actions/flow@v0.1.57
        with:
          workflow: pre-commit.yml
