name: Bump version

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"] # Name of the test workflow
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        uses: cvxgrp/.github/actions/uv/tag@v2.0.11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_package: 'false'
